services:
  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=5000
      - API_URL=https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api
      - API_VERSION=v1
      - TRANSACTION_FEE=0.95
    command: npm run dev:docker

  frontend:
    build: 
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_BACKEND_API_URL=http://localhost:5000
      - REACT_APP_CURRENCY_BIRD_API_URL=https://elb.currencybird.cl/apigateway-cb/api/public
      - WATCHPACK_POLLING=true
    command: npm start

  backend-tests:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
    command: npm test
